#!/usr/bin/env bash
# Script that transfers a file from Holberton's client to a server
# It accepts four arguments:
# + The PATH to the file to be transferred
# + The IP of the server that the transfer is being made
# + The username scp connects with
# + The PATH to the private key that scp uses

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
